# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --display_data=true
    # <- Optional: specify video codec (h264, hevc, libsvtav1). Default is libsvtav1. \
    # --dataset.vcodec=h264 \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so_follower \
  --robot.left_arm_config.port=/dev/tty.usbmodem5A460822851 \
  --robot.right_arm_config.port=/dev/tty.usbmodem5A460814411 \
  --robot.id=bimanual_follower \
  --robot.left_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 3, "width": 640, "height": 480, "fps": 30},
  }' --robot.right_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30},
    front: {"type": "opencv", "index_or_path": 4, "width": 640, "height": 480, "fps": 30},
  }' \
  --teleop.type=bi_so_leader \
  --teleop.left_arm_config.port=/dev/tty.usbmodem5A460852721 \
  --teleop.right_arm_config.port=/dev/tty.usbmodem5A460819811 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

import logging
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.reachy2_camera.configuration_reachy2_camera import Reachy2CameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.utils import INFO_PATH, build_dataset_frame, combine_feature_dicts
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_so_follower,
    earthrover_mini_plus,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    reachy2,
    so_follower,
    unitree_g1,
)
from lerobot.robots.aloha_follower import AlohaFollower, AlohaFollowerConfig  # noqa: F401
from lerobot.robots.xarm_follower import XarmFollower, XarmFollowerConfig  # noqa: F401
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_so_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    omx_leader,
    reachy2_teleoperator,
    so_leader,
)
from lerobot.teleoperators.aloha_leader import (  # noqa: F401
    AlohaLeader,
    AlohaLeaderConfig,
    BiAlohaLeader,
    BiAlohaLeaderConfig,
)
from lerobot.teleoperators.gello_leader import GelloLeader, GelloLeaderConfig  # noqa: F401
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, HF_LEROBOT_HOME, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.robot_utils import precise_sleep
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub (default False to avoid auth errors).
    push_to_hub: bool = False
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Video codec for encoding videos. Options: 'h264', 'hevc', 'libsvtav1'.
    # Use 'h264' for faster encoding on systems where AV1 encoding is CPU-heavy.
    vcodec: str = "libsvtav1"
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Display data on a remote Rerun server
    display_ip: str | None = None
    # Port of the remote Rerun server
    display_port: int | None = None
    # Whether to  display compressed images in Rerun
    display_compressed_images: bool = False
    # Use vocal synthesis to read events (disabled by default to avoid Speech Dispatcher errors).
    play_sounds: bool = False
    # Resume recording on an existing dataset.
    resume: bool = False
    # Load initial-state contour overlays from initial_states_overlay.py output.
    select: bool = False
    # Directory containing initial_states_overlay.py output (masks, contours, etc.).
    initial_states_dir: str | Path | None = "visual_match/initial_states"
    # Object name matching the segmentation prompt used in initial_states_overlay.py.
    object_name: str = "mug"

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")

        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")

            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    display_compressed_images: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(
                    t,
                    (
                        so_leader.SO100Leader
                        | so_leader.SO101Leader
                        | koch_leader.KochLeader
                        | omx_leader.OmxLeader
                    ),
                )
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # Reset policy and processor if they are provided
    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    timestamp = 0
    start_episode_t = time.perf_counter()
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        # Get robot observation
        obs = robot.get_observation()

        # Applies a pipeline to the raw robot observation, default is IdentityProcessor
        obs_processed = robot_observation_processor(obs)

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, obs_processed, prefix=OBS_STR)

        # Get action from either policy or teleop
        if policy is not None and preprocessor is not None and postprocessor is not None:
            action_values = predict_action(
                observation=observation_frame,
                policy=policy,
                device=get_safe_torch_device(policy.config.device),
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                use_amp=policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )

            act_processed_policy: RobotAction = make_robot_action(action_values, dataset.features)

        elif policy is None and isinstance(teleop, Teleoperator):
            act = teleop.get_action()

            # Applies a pipeline to the raw teleop action, default is IdentityProcessor
            act_processed_teleop = teleop_action_processor((act, obs))

        elif policy is None and isinstance(teleop, list):
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)
            act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
            act_processed_teleop = teleop_action_processor((act, obs))
        else:
            logging.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        # Applies a pipeline to the action, default is IdentityProcessor
        if policy is not None and act_processed_policy is not None:
            action_values = act_processed_policy
            robot_action_to_send = robot_action_processor((act_processed_policy, obs))
        else:
            action_values = act_processed_teleop
            robot_action_to_send = robot_action_processor((act_processed_teleop, obs))

        # Send action to robot
        _sent_action = robot.send_action(robot_action_to_send)

        # Write to dataset
        if dataset is not None:
            # When teleoperating, save the robot's own observation state as the
            # action (not the teleoperator reading).  This keeps action and
            # observation in the same coordinate frame and avoids the GELLO-xArm
            # offset problem.  For policy deployment the predicted action is
            # already in robot frame, so use it directly.
            if policy is not None:
                action_to_record = action_values
            else:
                # Re-read robot state right after the command so the recorded
                # action reflects the target the robot is actually tracking.
                obs_after = robot.get_observation()
                obs_after_processed = robot_observation_processor(obs_after)
                action_to_record = obs_after_processed

            action_frame = build_dataset_frame(dataset.features, action_to_record, prefix=ACTION)
            frame = {**observation_frame, **action_frame, "task": single_task}
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(
                observation=obs_processed, action=action_values, compress_images=display_compressed_images
            )

        dt_s = time.perf_counter() - start_loop_t
        precise_sleep(max(1 / fps - dt_s, 0.0))

        timestamp = time.perf_counter() - start_episode_t


def load_initial_state_contours(
    initial_states_dir: str | Path | None = None,
    object_name: str = "mug",
) -> list:
    """
    Load per-episode object contours from masks generated by initial_states_overlay.py.

    Each element of the returned list corresponds to one training episode and
    contains the cv2 contour arrays extracted from its binary mask.  Episodes
    whose mask file is missing or empty yield an empty list.

    Args:
        initial_states_dir: Directory produced by initial_states_overlay.py.
        object_name: Sub-directory name matching the TEXT_PROMPT used during
            segmentation (default ``"mug"``).

    Returns:
        list_of_contours – list (one entry per episode, sorted by episode
        index) of ``list[np.ndarray]`` contour arrays.
    """
    import cv2
    import numpy as np

    if initial_states_dir is None:
        raise ValueError(
            "--initial_states_dir is required when --select=true. "
            "Point it to the visual_match/initial_states/ directory."
        )
    masks_dir = Path(initial_states_dir) / object_name / "individual_masks"
    if not masks_dir.exists():
        raise FileNotFoundError(
            f"Mask directory not found: {masks_dir}\n"
            "Run initial_states_overlay.py first to generate masks."
        )

    mask_files = sorted(masks_dir.glob("ep_*_mask.png"))
    if not mask_files:
        raise FileNotFoundError(f"No mask files found in: {masks_dir}")

    list_of_contours = []
    for mask_path in mask_files:
        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        if mask is None:
            list_of_contours.append([])
            continue
        _, binary = cv2.threshold(mask, 127, 255, cv2.THRESH_BINARY)
        contours, _ = cv2.findContours(
            binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
        )
        list_of_contours.append(list(contours))

    ep_ids = [
        int(p.stem.replace("ep_", "").replace("_mask", "")) for p in mask_files
    ]
    logging.info(
        f"Loaded contours for {len(list_of_contours)} episodes "
        f"(eps {min(ep_ids)}–{max(ep_ids)}) from {masks_dir}"
    )
    return list_of_contours


def select_contours_ui(
    list_of_contours: list,
    num_eval_episodes: int,
    initial_states_dir: str | Path | None = None,
    object_name: str = "mug",
) -> tuple[list, list[int]]:
    """
    Interactive UI for selecting which training-episode contours to evaluate.

    Displays the all_episodes_grid image generated by initial_states_overlay.py.
    The user clicks on grid cells to select / deselect episodes.  Selected cells
    are highlighted in green.  Press ENTER to confirm or ESC to cancel.

    Returns:
        (selected_contours, selected_indices)
    """
    import math
    import cv2
    import numpy as np

    if initial_states_dir is None:
        raise ValueError(
            "--initial_states_dir is required when --select=true. "
            "Point it to the visual_match/initial_states/ directory."
        )
    grid_path = Path(initial_states_dir) / object_name / "all_episodes_grid.png"
    if not grid_path.exists():
        raise FileNotFoundError(
            f"Grid image not found: {grid_path}\n"
            "Run initial_states_overlay.py first."
        )

    grid_img = cv2.imread(str(grid_path))
    if grid_img is None:
        raise RuntimeError(f"Failed to read grid image: {grid_path}")

    n = len(list_of_contours)
    cols = math.ceil(math.sqrt(n))
    rows = math.ceil(n / cols)
    grid_h, grid_w = grid_img.shape[:2]
    thumb_w = grid_w // cols
    thumb_h = grid_h // rows

    # Burn episode labels and dim cells with no contour
    base_img = grid_img.copy()
    for idx in range(n):
        r, c = divmod(idx, cols)
        x0, y0 = c * thumb_w, r * thumb_h
        has_contour = bool(list_of_contours[idx])
        if not has_contour:
            overlay = base_img.copy()
            cv2.rectangle(overlay, (x0, y0), (x0 + thumb_w, y0 + thumb_h), (80, 80, 80), -1)
            cv2.addWeighted(overlay, 0.6, base_img, 0.4, 0, base_img)
        cv2.putText(
            base_img, str(idx), (x0 + 4, y0 + 16),
            cv2.FONT_HERSHEY_SIMPLEX, 0.45, (255, 255, 255), 1, cv2.LINE_AA,
        )

    selected: set[int] = set()
    display = base_img.copy()
    window_name = "Select Initial States"

    def _redraw():
        nonlocal display
        display = base_img.copy()
        for idx in selected:
            r, c = divmod(idx, cols)
            x0, y0 = c * thumb_w, r * thumb_h
            overlay = display.copy()
            cv2.rectangle(overlay, (x0, y0), (x0 + thumb_w, y0 + thumb_h), (0, 200, 0), -1)
            cv2.addWeighted(overlay, 0.25, display, 0.75, 0, display)
            cv2.rectangle(display, (x0 + 1, y0 + 1),
                          (x0 + thumb_w - 2, y0 + thumb_h - 2), (0, 255, 0), 3)
        remaining = num_eval_episodes - len(selected)
        status = (f"Selected {len(selected)}/{num_eval_episodes}  |  "
                  f"{'ENTER to confirm' if remaining <= 0 else f'{remaining} more needed'}  |  "
                  f"Click to toggle  |  ESC to cancel")
        cv2.rectangle(display, (0, grid_h - 30), (grid_w, grid_h), (40, 40, 40), -1)
        cv2.putText(display, status, (8, grid_h - 8),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.55, (220, 220, 220), 1, cv2.LINE_AA)
        cv2.imshow(window_name, display)

    def _on_mouse(event, x, y, flags, param):
        if event != cv2.EVENT_LBUTTONDOWN:
            return
        col = x // thumb_w
        row = y // thumb_h
        idx = row * cols + col
        if idx >= n:
            return
        if not list_of_contours[idx]:
            return
        if idx in selected:
            selected.discard(idx)
        elif len(selected) < num_eval_episodes:
            selected.add(idx)
        _redraw()

    cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
    cv2.resizeWindow(window_name, min(grid_w, 1200), min(grid_h + 30, 900))
    cv2.setMouseCallback(window_name, _on_mouse)
    _redraw()

    logging.info(f"Select {num_eval_episodes} episodes from the grid, then press ENTER.")

    while True:
        key = cv2.waitKey(50) & 0xFF
        if key in (13, 10):
            if len(selected) == 0:
                continue
            break
        if key == 27:
            selected.clear()
            break

    cv2.destroyWindow(window_name)
    cv2.waitKey(1)

    selected_indices = sorted(selected)
    selected_contours = [list_of_contours[i] for i in selected_indices]
    logging.info(f"Selected {len(selected_contours)} episodes: {selected_indices}")
    return selected_contours, selected_indices


def warmup_contour_alignment(
    robot,
    contour: list,
    events: dict,
    cam_key: str = "cam_high",
    alpha: float = 0.4,
) -> None:
    """
    Live RealSense alignment window: overlay a target contour on the camera feed.

    Continuously captures frames from the robot's stationary camera and draws
    the target contour with alpha blending so the user can physically move the
    object to match.  Blocks until RIGHT arrow (proceed) or ESC (quit).

    Args:
        robot: Connected robot instance (must have ``cameras[cam_key]``).
        contour: List of cv2 contour arrays to overlay.
        events: Keyboard event dict from :func:`init_keyboard_listener`.
        cam_key: Camera key in ``robot.cameras`` (default ``"cam_high"``).
        alpha: Blending weight for the contour fill overlay.
    """
    import cv2

    camera = robot.cameras.get(cam_key)
    if camera is None:
        logging.warning(
            f"Camera '{cam_key}' not found on robot (available: {list(robot.cameras)}). "
            "Skipping contour alignment overlay."
        )
        return

    window_name = "Align Object to Contour"
    cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
    cv2.resizeWindow(window_name, 640, 480)

    logging.info("Align the mug with the contour. Press RIGHT ARROW when ready.")

    while not events["right_arrow"] and not events["stop_recording"]:
        try:
            frame_rgb = camera.read()
        except Exception:
            continue

        frame_bgr = cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2BGR)

        overlay = frame_bgr.copy()
        cv2.drawContours(overlay, contour, -1, (0, 255, 0), -1)
        cv2.addWeighted(overlay, alpha, frame_bgr, 1.0 - alpha, 0, frame_bgr)
        cv2.drawContours(frame_bgr, contour, -1, (0, 255, 0), 2)

        h = frame_bgr.shape[0]
        cv2.rectangle(frame_bgr, (0, h - 32), (frame_bgr.shape[1], h), (40, 40, 40), -1)
        cv2.putText(
            frame_bgr,
            "Align the mug with the contour. Press RIGHT ARROW when ready.",
            (8, h - 9),
            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (220, 220, 220), 1, cv2.LINE_AA,
        )

        cv2.imshow(window_name, frame_bgr)
        cv2.waitKey(30)

    cv2.destroyWindow(window_name)
    cv2.waitKey(1)


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)
    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )

    dataset = None
    listener = None

    try:
        # Compute dataset root (same logic as LeRobotDatasetMetadata.create)
        dataset_root = (
            Path(cfg.dataset.root) if cfg.dataset.root is not None else HF_LEROBOT_HOME / cfg.dataset.repo_id
        )
        dataset_exists = dataset_root.exists() and (dataset_root / INFO_PATH).is_file()

        if cfg.resume:
            if not dataset_exists:
                raise FileNotFoundError(
                    f"Cannot resume: no existing dataset found at {dataset_root}. "
                    "Remove --resume to create a new dataset."
                )
            dataset = LeRobotDataset(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

            if hasattr(robot, "cameras") and len(robot.cameras) > 0:
                dataset.start_image_writer(
                    num_processes=cfg.dataset.num_image_writer_processes,
                    num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                )
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            # Create empty dataset
            if dataset_exists:
                raise FileExistsError(
                    f"Dataset already exists at {dataset_root}. "
                    "Use --resume=true to continue recording."
                )
            sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

        # Load pretrained policy
        policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
        preprocessor = None
        postprocessor = None
        if cfg.policy is not None:
            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )

        robot.connect()
        if teleop is not None:
            teleop.connect()

        listener, events = init_keyboard_listener()

        # Load initial-state contours and open selection UI when --select is used
        list_of_contours = None
        selected_contours = None
        selected_episode_indices = None
        if cfg.select:
            list_of_contours = load_initial_state_contours(
                initial_states_dir=cfg.initial_states_dir,
                object_name=cfg.object_name,
            )
            selected_contours, selected_episode_indices = select_contours_ui(
                list_of_contours,
                cfg.dataset.num_episodes,
                initial_states_dir=cfg.initial_states_dir,
                object_name=cfg.object_name,
            )
            if not selected_contours:
                logging.warning("No episodes selected, exiting.")
                return dataset
            if len(selected_contours) != cfg.dataset.num_episodes:
                raise ValueError(
                    f"Selected {len(selected_contours)} contours but "
                    f"num_episodes={cfg.dataset.num_episodes}. Must be equal."
                )

        with VideoEncodingManager(dataset):
            recorded_episodes = 0
            # State machine: WARMUP <-> RECORDING (ALOHA-style)
            state = "WARMUP"

            while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:

                if state == "WARMUP":
                    warmup_contour = None
                    if selected_contours is not None and recorded_episodes < len(selected_contours):
                        warmup_contour = selected_contours[recorded_episodes]

                    print(f"\n{'='*50}")
                    print(f"WARMUP - Episode {recorded_episodes + 1}/{cfg.dataset.num_episodes}")
                    if warmup_contour:
                        src_ep = selected_episode_indices[recorded_episodes]
                        print(f"  Contour: selected_contours[{recorded_episodes}]  "
                              f"(training ep {src_ep})")
                        print(f"  Align the mug with the contour. Press RIGHT ARROW when ready.")
                    else:
                        print(f"  Press RIGHT to start recording")
                    print(f"{'='*50}")

                    if warmup_contour:
                        # ── RealSense alignment window with contour overlay ──
                        events["right_arrow"] = False
                        events["left_arrow"] = False
                        events["exit_early"] = False
                        warmup_contour_alignment(
                            robot, warmup_contour, events,
                        )
                        if events["stop_recording"]:
                            break
                        events["right_arrow"] = False
                        events["exit_early"] = False
                        state = "RECORDING"
                        print(">>> Start recording")
                    else:
                        # ── Standard warmup (teleop idle, wait for RIGHT) ──
                        # During deployment (policy provided) do NOT follow the GELLO –
                        # the robot should hold its current position until recording
                        # begins and the policy takes over.
                        warmup_teleop = None if policy is not None else teleop
                        record_loop(
                            robot=robot,
                            events=events,
                            fps=cfg.dataset.fps,
                            teleop_action_processor=teleop_action_processor,
                            robot_action_processor=robot_action_processor,
                            robot_observation_processor=robot_observation_processor,
                            teleop=warmup_teleop,
                            control_time_s=float("inf"),
                            single_task=cfg.dataset.single_task,
                            display_data=cfg.display_data,
                        )

                        if events["stop_recording"]:
                            break

                        if events["right_arrow"]:
                            events["right_arrow"] = False
                            events["exit_early"] = False
                            state = "RECORDING"
                            print(">>> Start recording")

                elif state == "RECORDING":
                    # RECORDING state: record episode, wait for right arrow (save) or left arrow (discard)
                    # Episode auto-saves when episode_time_s is reached (same as RIGHT arrow).
                    print(f"\n{'='*50}")
                    print(f"RECORDING episode {dataset.num_episodes} - RIGHT=save, LEFT=discard, ESC=stop")
                    print(f"  (auto-save after {cfg.dataset.episode_time_s}s)")
                    print(f"{'='*50}")

                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        policy=policy,
                        preprocessor=preprocessor,
                        postprocessor=postprocessor,
                        dataset=dataset,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                        display_compressed_images=display_compressed_images,
                    )

                    if events["stop_recording"]:
                        break

                    if events["left_arrow"]:
                        # Discard episode and go back to warmup
                        events["left_arrow"] = False
                        events["rerecord_episode"] = False
                        events["exit_early"] = False
                        dataset.clear_episode_buffer()
                        print(">>> Episode discarded")
                        state = "WARMUP"

                    else:
                        # Save episode: RIGHT arrow pressed OR episode_time_s reached
                        events["right_arrow"] = False
                        events["exit_early"] = False
                        dataset.save_episode()
                        recorded_episodes += 1
                        print(f">>> Episode saved ({recorded_episodes}/{cfg.dataset.num_episodes})")
                        state = "WARMUP"
    finally:
        print("\n>>> Stop recording")

        if dataset:
            dataset.finalize()

        if robot.is_connected:
            robot.disconnect()
        if teleop and teleop.is_connected:
            teleop.disconnect()

        if not is_headless() and listener:
            listener.stop()

        if cfg.dataset.push_to_hub and dataset is not None:
            dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

        print(">>> Done")
    return dataset


def main():
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()
